
apiKey: AIzaSyBqmDyUUQFtUizN1-3Fsdr5-0b7CfRYXlc
authDomain: sentimentanalysis-997b4.firebaseapp.com
databaseURL: https://sentimentanalysis-997b4.firebaseio.com
projectId: sentimentanadlysis-997b4
storageBucket: sentimentanalysis-997b4.appspot.com
messagingSenderId: 386712053305
appId': 1:386712053305:web:8837eb760468e13d970fe8
measurementId: G-B2LNH8BWNT